# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:  
        node-version: '14'
        registry-url: 'https://npm.pkg.github.com'          
        # Defaults to the user or organization that owns the workflow file
        scope: '@hugobernardoni'
    - name: Test
      run: yarn install --frozen-lockfile
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}   
    - name: Run
      run: node index.js
